# Generated by Django 4.0.3 on 2022-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('level', models.IntegerField(default=None)),
                ('time', models.TimeField(default=None)),
            ],
        ),
    ]
