# Generated by Django 4.0.3 on 2022-09-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
