# Generated by Django 4.0.3 on 2022-09-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_leaderboard_level_alter_leaderboard_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
