# Generated by Django 4.0.3 on 2022-09-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_leaderboard_level_alter_leaderboard_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
