# Generated by Django 4.0.3 on 2022-09-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_leaderboard_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='time',
            new_name='completion',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='start',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
